
services:

 app_proxy:
   environment:
     # The format here is: <app-id>_<docker-service-name>_1
     APP_HOST: hs123-pyload_1
     APP_PORT: 8996
    
 server:
    image: lscr.io/linuxserver/pyload-ng:latest
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Asia/Tehran
     volumes:
       - ${APP_DATA_DIR}/data/config:/config
       - ${APP_DATA_DIR}/data/downloads:/downloads
